### ISSUE TITLE
gs conflict with GhostScript in Linux

### ISSUE THREAD

**Issue by maxidr** [soveran/gs#8]
In fact this not a bug, but I can't use this tool because Linux have installed GhostScript by default and used this name as executable (gs).  You know some manner of resolve this conflict?

Thanks

**Comment by willywg** [comment]
I have the same problem on oSX

ruby-2.1.2 $ gs
GPL Ghostscript 9.04 (2011-08-05)
Copyright (C) 2011 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.

**Comment by soveran** [comment]
Hello @willywg, the gem is also released as `gemset`, so you can `gem install gemset`. Alternatively, you can just copy the `gs` file, rename it to any other name and put it in your `PATH`. For example, a lot of people directly use `curl` to grab the file, then put it in `~/bin`.
